# Generated by Django 3.1.1 on 2020-09-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
