# Generated by Django 3.1.1 on 2020-09-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reciever',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
