# Generated by Django 3.1.1 on 2020-09-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200905_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
    ]
