# Generated by Django 3.1.1 on 2020-09-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transaction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reciever',
            field=models.IntegerField(),
        ),
    ]
