# Generated by Django 3.1.1 on 2020-09-05 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_auto_20200905_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reciever_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
